import {
  UserProfile,
  Task,
  Deadline,
  Hackathon,
  Transaction,
  CalendarEvent,
  Balances,
} from '../types';

const STORAGE_KEYS = {
  PROFILE: 'lifedesk_profile',
  TASKS: 'lifedesk_tasks',
  DEADLINES: 'lifedesk_deadlines',
  HACKATHONS: 'lifedesk_hackathons',
  TRANSACTIONS: 'lifedesk_transactions',
  EVENTS: 'lifedesk_events',
  BALANCES: 'lifedesk_balances',
  THEME: 'lifedesk_theme',
  AUTH: 'lifedesk_auth',
};

export const INITIAL_PROFILE: UserProfile = {
  id: 'usr_aryan_01',
  fullName: 'Aryan Sharma',
  email: 'aryan.sharma@campus.edu.in',
  phone: '+91 98765 43210',
  college: 'National Institute of Technology, Delhi',
  course: 'B.Tech - Computer Science & Engineering',
  currentSemester: 'Sem VII',
  bio: 'Systems geek, competitive hackathon builder & Edge AI enthusiast.',
  avatarUrl: 'https://lh3.googleusercontent.com/aida/AEtjO1UEgUlihmPnmz7-G4PHbl3pC1m1eEBx9V7IfsB6x7Bu1e1qkGgR4JntQeww1cNwkHE22XSFgWKmV-Swd1ODRC7FAnfZa_RQ7rxRwOKsPzqZJ6g71fU3J8hPEjcPb9n6MZvN2HZJtaP2fCtsYv4luUc3WnBPVwe0sn6AeMzTfbQQQAcP3hr6yjcM27a_4bIsS-8abxk3kWdA-bItHgPBzr0faPFmVagKKMjUnF7PNdrb-YqkGtQ06MQ2abHq2bAI-F-VKlth0God-A',
};

export const INITIAL_BALANCES: Balances = {
  upiBalance: 5000,
  cashBalance: 1500,
};

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    name: 'Submit OS Lab Practical Assignment',
    description: 'Page replacement algorithms & kernel tracing report',
    category: 'Practical',
    deadline: new Date(new Date().setHours(14, 0, 0, 0)).toISOString(),
    priority: 'Urgent',
    status: 'Not Started',
    notes: 'Include FIFO, LRU, Optimal simulation charts',
    tags: ['OS', 'Linux', 'Lab'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    name: 'Review Machine Learning PPT',
    description: 'Transformer attention visuals & validation loss curves',
    category: 'Presentation',
    deadline: new Date(new Date().setHours(18, 0, 0, 0)).toISOString(),
    priority: 'High',
    status: 'Not Started',
    notes: 'Check slide 14 cross-entropy derivation',
    tags: ['ML', 'Seminar'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    name: 'Team Sync for Hackathon Prototype',
    description: 'Google Meet link with Rishabh & Ananya',
    category: 'Hackathon',
    deadline: new Date(new Date().setHours(20, 30, 0, 0)).toISOString(),
    priority: 'Medium',
    status: 'Not Started',
    notes: 'Discuss ONNX runtime integration on Jetson Nano',
    tags: ['SIH', 'Hardware'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    name: 'Distributed Systems Lecture Notes Revision',
    description: 'Raft consensus algorithm leader election edge cases',
    category: 'College',
    deadline: new Date(Date.now() + 86400000).toISOString(),
    priority: 'Medium',
    status: 'Not Started',
    notes: 'Read Diego Ongaro paper section 5',
    tags: ['Theory', 'Exams'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    name: 'Devfolio HackSprint Smart Contract Tests',
    description: 'Hardhat unit testing for staking & bounty vaults',
    category: 'Project',
    deadline: new Date(Date.now() + 86400000 * 3).toISOString(),
    priority: 'High',
    status: 'In Progress',
    notes: 'Ensure 95% branch coverage before M2 submission',
    tags: ['Web3', 'HackSprint'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-6',
    name: 'Cloud Computing AWS Lambda Architecture Sketch',
    description: 'Serverless event triggers for OCR pipeline',
    category: 'Assignment',
    deadline: new Date(Date.now() + 86400000 * 4).toISOString(),
    priority: 'Low',
    status: 'Not Started',
    tags: ['Cloud', 'AWS'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-7',
    name: 'Hostel Mess Bill Verification',
    description: 'Cross-check monthly coupon redemption with warden list',
    category: 'Personal',
    deadline: new Date(Date.now() - 3600000 * 5).toISOString(),
    priority: 'Low',
    status: 'Completed',
    tags: ['Hostel'],
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_DEADLINES: Deadline[] = [
  {
    id: 'dl-1',
    title: 'Computer Networks Quiz',
    description: 'Subnetting & TCP Flow Control',
    category: 'Exam',
    dueDate: new Date(Date.now() + 86400000 * 1).toISOString(),
    status: 'Due Soon',
    taskId: 'task-4',
  },
  {
    id: 'dl-2',
    title: 'Cloud Capstone Report',
    description: 'In 3 days • AWS Lambda Architectures',
    category: 'Project',
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    status: 'Upcoming',
    taskId: 'task-6',
  },
  {
    id: 'dl-3',
    title: 'Devfolio HackSprint M2',
    description: 'In 5 days • Smart contract test suite',
    category: 'Hackathon',
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: 'Upcoming',
    taskId: 'task-5',
  },
  {
    id: 'dl-4',
    title: 'Compiler Design Lab Viva',
    description: 'Lexical analysis & LR(1) parser construction',
    category: 'Practical',
    dueDate: new Date(Date.now() + 86400000 * 8).toISOString(),
    status: 'Upcoming',
  },
];

export const INITIAL_HACKATHONS: Hackathon[] = [
  {
    id: 'hack-1',
    name: 'Smart India Hackathon (SIH 2024)',
    organizer: 'Ministry of Education & AICTE',
    registrationDeadline: new Date(Date.now() - 86400000 * 14).toISOString(),
    currentStage: 'Pitch in 4d',
    status: 'In Progress',
    trackName: 'Hardware Acceleration Track',
    deliverable: 'Deliverable: Edge AI deployment demo',
    bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjtBuuCmgokrKA9Lsf3TGWYap2143gafT_Gpi5128W1tu-nIl3lyVapkBGXHrkQSEHtsUtayorGPiIwQQYkGCaxGfpNp1BsLwcwRTmo_2LIQqJhKsfp6KHMaSc6JoAWspotgRayRG31wCe4J_1AlLrFcLo5aH6w7zd2wZUY-0C5Vj_kqLO5Dc17mSWR6jWfvHN6etHbr0IPVyq07Zy1C1cV_b1kxipUXfCn4YPH7t6fNheOF-WMiow',
    notes: 'Team Name: CyberForge. Team Lead: Aryan. Focus on low-power quantized YOLOv8 inference.',
    milestones: [
      {
        id: 'ms-1-1',
        hackathonId: 'hack-1',
        stage: 'Registration',
        title: 'College SPOC Endorsement & Registration',
        date: '2026-08-25',
        status: 'Completed',
        notes: 'Submitted NOC signed by HoD',
      },
      {
        id: 'ms-1-2',
        hackathonId: 'hack-1',
        stage: 'Idea Submission',
        title: '3-Page Executive Summary Submission',
        date: '2026-09-02',
        status: 'Completed',
        notes: 'Focus on industrial edge vision pipeline',
      },
      {
        id: 'ms-1-3',
        hackathonId: 'hack-1',
        stage: 'PPT Submission',
        title: 'Architecture & Circuit Topology Deck',
        date: '2026-09-12',
        status: 'Completed',
        notes: 'Included thermal dissipation benchmarks',
      },
      {
        id: 'ms-1-4',
        hackathonId: 'hack-1',
        stage: 'Screening Quiz',
        title: 'Technical Screening & Domain Evaluation',
        date: '2026-09-18',
        status: 'Completed',
        notes: 'Scored 94/100 in Embedded Systems module',
      },
      {
        id: 'ms-1-5',
        hackathonId: 'hack-1',
        stage: 'Prototype',
        title: 'Functional Embedded Hardware Working Demo',
        date: '2026-09-24',
        status: 'Current',
        notes: 'Benchmarking latency < 28ms per frame',
        associatedTaskId: 'task-3',
      },
      {
        id: 'ms-1-6',
        hackathonId: 'hack-1',
        stage: 'Final Submission',
        title: 'GitHub Repository & Demo Video Upload',
        date: '2026-09-26',
        status: 'Pending',
        notes: 'Must include open source MIT license & setup guide',
      },
      {
        id: 'ms-1-7',
        hackathonId: 'hack-1',
        stage: 'Final Pitch',
        title: 'Grand Finale Live Jury Presentation',
        date: '2026-09-27',
        status: 'Pending',
        notes: '10 min presentation + 5 min Q&A in auditorium',
      },
    ],
  },
  {
    id: 'hack-2',
    name: 'Devfolio HackSprint 2024',
    organizer: 'Devfolio & Polygon Labs',
    registrationDeadline: new Date(Date.now() - 86400000 * 20).toISOString(),
    currentStage: 'Milestone 2 in 5d',
    status: 'In Progress',
    trackName: 'DeFi & Micro-Grants',
    deliverable: 'Automated campus student project micro-endowments',
    bannerImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    notes: 'Solidity contracts deployed on Mumbai / Amoy testnet',
    milestones: [
      {
        id: 'ms-2-1',
        hackathonId: 'hack-2',
        stage: 'Registration',
        title: 'Team onboarding & Discord sync',
        date: '2026-09-01',
        status: 'Completed',
      },
      {
        id: 'ms-2-2',
        hackathonId: 'hack-2',
        stage: 'Idea Submission',
        title: 'Litepaper & System Architecture',
        date: '2026-09-10',
        status: 'Completed',
      },
      {
        id: 'ms-2-3',
        hackathonId: 'hack-2',
        stage: 'Prototype',
        title: 'M2: Core Smart Contract Tests & Subgraph',
        date: '2026-09-30',
        status: 'Current',
        associatedTaskId: 'task-5',
      },
      {
        id: 'ms-2-4',
        hackathonId: 'hack-2',
        stage: 'Final Submission',
        title: 'Live dApp deployment on testnet',
        date: '2026-10-05',
        status: 'Pending',
      },
      {
        id: 'ms-2-5',
        hackathonId: 'hack-2',
        stage: 'Final Pitch',
        title: 'Virtual Demo Day & Investor AMA',
        date: '2026-10-08',
        status: 'Pending',
      },
    ],
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'expense',
    amount: 180,
    description: 'Canteen Lunch',
    category: 'Food',
    date: new Date().toISOString().split('T')[0],
    time: '1:15 PM',
    paymentSource: 'UPI',
    status: 'Settled',
    notes: 'Thali & Fresh Lime with batchmates',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 450,
    description: 'Bus Pass Recharge',
    category: 'Travel',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    time: 'Yesterday',
    paymentSource: 'UPI',
    status: 'Settled',
    notes: 'Monthly student bus pass DTC',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 120,
    description: 'Printed Circuit Lab Manual',
    category: 'Study Material',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    time: 'Sep 24',
    paymentSource: 'Cash',
    status: 'Settled',
    notes: 'Xerox Shop spiral binding',
  },
  {
    id: 'tx-4',
    type: 'expense',
    amount: 0,
    description: 'GitHub Copilot Student',
    category: 'Software',
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    time: 'Student Developer Pack',
    paymentSource: 'Card',
    status: 'Free Tier',
    notes: 'Verified with university @campus.edu.in email',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 2100,
    description: 'Jetson Nano Development Board Accessory Kit',
    category: 'Hackathon',
    date: new Date(Date.now() - 86400000 * 6).toISOString().split('T')[0],
    time: 'Sep 17',
    paymentSource: 'Card',
    status: 'Settled',
    notes: 'Billed on student credit card (Billed separately • No debit from liquid)',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 550,
    description: 'Hostel Wi-Fi Booster Subscription',
    category: 'Hostel / Room',
    date: new Date(Date.now() - 86400000 * 10).toISOString().split('T')[0],
    time: 'Sep 13',
    paymentSource: 'UPI',
    status: 'Settled',
    notes: 'High speed fiber plan for hackathon prep',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 250,
    description: 'Late Night Coffee & Samosas',
    category: 'Food',
    date: new Date(Date.now() - 86400000 * 12).toISOString().split('T')[0],
    time: 'Sep 11',
    paymentSource: 'Cash',
    status: 'Settled',
    notes: 'Night canteen during lab test prep',
  },
  {
    id: 'tx-8',
    type: 'income',
    amount: 4000,
    description: 'Monthly Pocket Money from Parents',
    category: 'Pocket Money',
    date: new Date(Date.now() - 86400000 * 15).toISOString().split('T')[0],
    time: 'Sep 8',
    destination: 'UPI',
    status: 'Settled',
    notes: 'Deposited to SBI student account',
  },
  {
    id: 'tx-9',
    type: 'transfer',
    amount: 1000,
    description: 'ATM Cash Withdrawal',
    category: 'Transfer',
    date: new Date(Date.now() - 86400000 * 14).toISOString().split('T')[0],
    time: 'Sep 9',
    transferFrom: 'UPI',
    transferTo: 'Cash',
    status: 'Settled',
    notes: 'For campus canteen & printing emergency cash',
  },
];

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Submit OS Lab Practical Assignment',
    description: 'Page replacement algorithms & kernel tracing report',
    category: 'Practical',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '14:00',
    type: 'task',
    referenceId: 'task-1',
  },
  {
    id: 'evt-2',
    title: 'Review Machine Learning PPT',
    description: 'Transformer attention visuals & validation loss curves',
    category: 'Presentation',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '18:00',
    type: 'task',
    referenceId: 'task-2',
  },
  {
    id: 'evt-3',
    title: 'Team Sync for Hackathon Prototype',
    description: 'Google Meet link with Rishabh & Ananya',
    category: 'Hackathon',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '20:30',
    type: 'task',
    referenceId: 'task-3',
  },
  {
    id: 'evt-4',
    title: 'Computer Networks Quiz',
    description: 'Subnetting & TCP Flow Control',
    category: 'Exam',
    startDate: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
    startTime: '10:00',
    type: 'deadline',
    referenceId: 'dl-1',
  },
  {
    id: 'evt-5',
    title: 'SIH 2024: Edge Hardware Demo Due',
    description: 'Deliverable: Edge AI deployment demo',
    category: 'Hackathon',
    startDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
    startTime: '17:00',
    type: 'hackathon',
    referenceId: 'hack-1',
  },
];

// Helper to load or initialize storage
export const getStoredData = <T>(key: string, fallback: T): T => {
  try {
    const item = localStorage.getItem(key);
    if (!item) {
      localStorage.setItem(key, JSON.stringify(fallback));
      return fallback;
    }
    return JSON.parse(item) as T;
  } catch (err) {
    console.warn(`Error loading ${key} from storage:`, err);
    return fallback;
  }
};

export const setStoredData = <T>(key: string, value: T): void => {
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (err) {
    console.warn(`Error saving ${key} to storage:`, err);
  }
};

export const storage = {
  getProfile: () => getStoredData<UserProfile>(STORAGE_KEYS.PROFILE, INITIAL_PROFILE),
  setProfile: (val: UserProfile) => setStoredData(STORAGE_KEYS.PROFILE, val),

  getTasks: () => getStoredData<Task[]>(STORAGE_KEYS.TASKS, INITIAL_TASKS),
  setTasks: (val: Task[]) => setStoredData(STORAGE_KEYS.TASKS, val),

  getDeadlines: () => getStoredData<Deadline[]>(STORAGE_KEYS.DEADLINES, INITIAL_DEADLINES),
  setDeadlines: (val: Deadline[]) => setStoredData(STORAGE_KEYS.DEADLINES, val),

  getHackathons: () => getStoredData<Hackathon[]>(STORAGE_KEYS.HACKATHONS, INITIAL_HACKATHONS),
  setHackathons: (val: Hackathon[]) => setStoredData(STORAGE_KEYS.HACKATHONS, val),

  getTransactions: () => getStoredData<Transaction[]>(STORAGE_KEYS.TRANSACTIONS, INITIAL_TRANSACTIONS),
  setTransactions: (val: Transaction[]) => setStoredData(STORAGE_KEYS.TRANSACTIONS, val),

  getEvents: () => getStoredData<CalendarEvent[]>(STORAGE_KEYS.EVENTS, INITIAL_EVENTS),
  setEvents: (val: CalendarEvent[]) => setStoredData(STORAGE_KEYS.EVENTS, val),

  getBalances: () => getStoredData<Balances>(STORAGE_KEYS.BALANCES, INITIAL_BALANCES),
  setBalances: (val: Balances) => setStoredData(STORAGE_KEYS.BALANCES, val),
};
